{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if eq .Values.ingress.type "nginx-kubernetes" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    {{- if eq .Values.ingress.type "nginx-org" }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: 'ServiceName={{ template "app.fullname" . }} rewrite=/'
    {{- end }}
    #nginx.org/redirect-to-https: "True" #dont work in minion, should be set in master
    #nginx.org/hsts-behind-proxy: "True" #dont work in minion or master despite documentation
  name: {{ template "app.fullname" . }}-ingress
spec:
  rules:
    - host: {{quote .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "app.fullname" . }}
                port:
                  number: {{ .Values.ui.servicePort }}
            path: {{ .Values.ingress.path }}{{- if eq .Values.ingress.type "nginx-kubernetes" }}(/|$)(.*){{- end }}
            pathType: Prefix
  {{- if .Values.ingress.tls.useExternal }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.useExternal | quote }}
  {{- end }}
{{- end }}
